# Exported from Render on 2024-10-09T03:43:06Z
services:
- type: web
  name: onetimesecret
  runtime: docker
  repo: https://github.com/jgoldfed/onetimesecret
  plan: starter
  envVars:
  - key: RACK_ENV
    sync: false
  - key: REDIS_URL
    sync: false
  - key: COLONEL
    sync: false
  - key: SSL
    sync: false
  - key: HOST
    sync: false
  region: oregon
  healthCheckPath: /
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"

- type: redis
  name: onetimesecret-redis
  plan: free
  region: oregon
  maxmemoryPolicy: allkeys-lru
  ipAllowList: []


